# 应用端口与名称配置
server:
  port: 8100
spring:
  application:
    name: demo-config-server
  cloud:
    config: # Config配置中心
      label: master
      server:
        git:
          uri: https://github.com/GitSarp/hotch-potch
          timeout: 10
          search-paths: clouddemo/configserver/config-center/{application}

# Eureka客户端配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
  instance:
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}

