eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/,http://localhost:1002/eureka/
  instance:
    #服务注册的实例id
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true

server:
  port: 6001
spring:
  application:
    name: service-zuul
  cloud:
    gateway:
      routes:
        - id: bulletscreen
          # 重点！/info必须使用http进行转发，lb代表从注册中心获取服务
          uri: lb://bullet
          predicates:
            # 重点！转发该路径！
            - Path=/bullet/info/**
        - id: bulletscreen
          # 重点！lb:ws://代表从注册中心获取服务，并且转发协议为websocket
          uri: lb:ws://bullet
          predicates:
            # 转发/bullet端点下的所有路径
            - Path=/bullet/**

        - id: bulletscreen2
          uri: lb:ws://bullet
          predicates:
            - Path=/bullet2/**

        - id: wsservice
          #ws://localhost:3000/sharedb?nodeid=ssq
          uri: lb:ws://ws-service
          predicates:
            - Path=/sharedb/**
        - id: wsservice2
          #ws://localhost:3000/cursors?nodeid=ssq
          uri: lb:ws://ws-service
          predicates:
            - Path=/cursors/**
# zuul路由转发，路由配置
#zuul:
#  routes:
#    api-a:
#      path: /client/**
#      serviceId: eureka-client
#    api-b:
#      path: /ms3/**
#      serviceId: ms3
#    api-c:
#      path: /ribbon/**
#      serviceId: ribboncall