# 无参数启动
spring:
  application:
    name: eureka-server
server:
  port: 1001
eureka:
  instance:
    #服务注册的实例id
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
  client:
    #自己不注册自己
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/

# 启动参数 --spring.profiles.active=server1
---
spring:
  profiles: server1
server:
  port: 1001
eureka:
  client:
    service-url:
      #两个server相互注册
      defaultZone: http://localhost:1002/eureka/
---
# 启动参数 --spring.profiles.active=server2
spring:
  profiles: server2
server:
  port: 1002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/
